### ISSUE TITLE
qt5 cyclic dependencies

### ISSUE THREAD

**Issue by xtraeme** [voidlinux/xbps#100]
Since the update to qt5-5.4.2, qt5 depends on qt5-sensors due to those sensor examples and qt5-sensors depends on qt5...

Would be nice to not introduce cyclic dependencies :-)

**Comment by pullmoll** [comment]
Ah, that's the cycle I didn't see. Sorry for not testing that extensively before.
So should the dependency of qt5-examples on qt5 just be removed?

**Comment by xtraeme** [comment]
No, the issue is this:

```
/usr/share/qt5/examples/sensors/grue/libgruesensor.so.1.0 -> /usr/share/qt5/examples/sensors/grue/libgruesensor.so.1.0.0
/usr/share/qt5/examples/sensors/grue/libgruesensor.so -> /usr/share/qt5/examples/sensors/grue/libgruesensor.so.1.0.0
/usr/share/qt5/examples/sensors/grue/libgruesensor.so.1 -> /usr/share/qt5/examples/sensors/grue/libgruesensor.so.1.0.0
```

1- Those files do not belong to qt5, should be in qt5-examples instead.
2- When moving those files to qt5-examples, noarch must be removed.

Please fix

**Comment by pullmoll** [comment]
Ok, will do.
I wonder why those libraries are built with -no-compile-examples, though. *sighs*

**Comment by pullmoll** [comment]
FYI: This takes longer than expected. I'm refactoring the `collect_examples()` code and probably even need to change the order of `${subpackages}`, because the libs are still in my local `qt5-5.4.2_2.xbps`.
Why did I even start to touch this? :)

**Comment by xtraeme** [comment]
The order of subpackages (unless overrided if the subpackages var is declared) is always alphabetically, and the main pkg being added as the last one.

**Comment by xtraeme** [comment]
I submitted this PR to the wrong repository... should have been void-packages. 

Closing it, thanks for your workaround.
