### ISSUE TITLE
xbps-uunshare breaks on musl when called by xbps-src due to differences in getopt

### ISSUE THREAD

**Issue by CMB** [voidlinux/xbps#102]
Basically, musl's getopt doesn't treat a command line like
command arg1 -- other_args
the same way glibc's getopt does.
The -- isn't removed.
You can see what I mean by grabbing this little program:
http://the-brannons.com/arg.c
Compile on both glibc and musl, and run
./a.out foo -- bar
Or
./a.out -b some_arg foo -- bar
And similar.

Maybe this is a musl upstream bug also.  I do not know.

**Comment by CMB** [comment]
According to
http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc,

GNU getopt permutes argv to pull options to the front,
ahead of non-option arguments. musl and the POSIX standard getopt stop
processing options at the first non-option argument with no permutation.

So this is not a musl upstream bug after all.
I'll send a PR that should fix the xbps tools that call getopt shortly.

**Comment by Gottox** [comment]
#103

**Comment by xtraeme** [comment]
Fixed by applying #103 

Thanks
