### ISSUE TITLE
Files may get created with the wrong permissions if umask is weird.

### ISSUE THREAD

**Issue by lodvaer** [voidlinux/xbps#106]
Looks like voidlinux/void-packages#835, only with the configure scripts.
<pre>
% xbps-install --version
XBPS: 0.46 API: 20150603 GIT: 7190a28
% pwd
/usr/share/terminfo/r
% ls -l
total 36
-rw-r--r-- 1 root root 2285 Jun  5 09:10 rxvt
-rw-r--r-- 1 root root 2499 Jun  5 09:10 rxvt-16color
-rw-r--r-- 1 root root 2427 Jun  5 09:10 rxvt-256color
-rw-r--r-- 1 root root 2425 Jun  5 09:10 rxvt-88color
-rw-r--r-- 1 root root 2145 Jun  5 09:10 rxvt-basic
-rw-r--r-- 1 root root 2229 Jun  5 09:10 rxvt-color
-rw-r--r-- 1 root root 2251 Jun  5 09:10 rxvt-cygwin
-rw-r--r-- 1 root root 2269 Jun  5 09:10 rxvt-cygwin-native
-rw-r--r-- 1 root root 2227 Jun  5 09:10 rxvt-xpm
% umask
077
% xbps-install rxvt-unicode-terminfo
...
[*] Configuring unpacked packages
rxvt-unicode-terminfo-9.21_7: configuring ...
2 entries written to /usr/share/terminfo
rxvt-unicode-terminfo-9.21_7: installed successfully.
...
% ls -l
total 48
-rw-r--r-- 1 root root 2285 Jun  5 09:10 rxvt
-rw-r--r-- 1 root root 2499 Jun  5 09:10 rxvt-16color
-rw-r--r-- 1 root root 2427 Jun  5 09:10 rxvt-256color
-rw-r--r-- 1 root root 2425 Jun  5 09:10 rxvt-88color
-rw-r--r-- 1 root root 2145 Jun  5 09:10 rxvt-basic
-rw-r--r-- 1 root root 2229 Jun  5 09:10 rxvt-color
-rw-r--r-- 1 root root 2251 Jun  5 09:10 rxvt-cygwin
-rw-r--r-- 1 root root 2269 Jun  5 09:10 rxvt-cygwin-native
-rw------- 1 root root 2208 Jun 26 11:58 rxvt-unicode
-rw------- 1 root root 2234 Jun 26 11:58 rxvt-unicode-256color
-rw-r--r-- 1 root root 3172 Jun 23 11:45 rxvt-unicode.terminfo
-rw-r--r-- 1 root root 2227 Jun  5 09:10 rxvt-xpm
</pre>
Also affects compiled python files.

**Comment by pulux** [comment]
umask in void is for users 0022, but if you do "su" then the umask is 0077, since 83b38fc69. If you then install software, this umask is used.

**Comment by chneukirchen** [comment]
Still, the hooks should run with a fixed umask.
