### ISSUE TITLE
Download/Install size required for xbps-install transaction

### ISSUE THREAD

**Issue by aarnt** [voidlinux/xbps#109]
Retrieve the download and install size required for a xbps-install transaction when using the "-n" (dry-run) option.
This can ease frontend GUI dev.

**Comment by aarnt** [comment]
Cool!!!

**Comment by xtraeme** [comment]
Note the size is in bytes, and there are 6 arguments; the last one being optional and only available when installing or updating:

`<pkgver> <action> <arch> <repository> <installed_size> <download_size>`
