### ISSUE TITLE
reproducable builds support

### ISSUE THREAD

**Issue by Gottox** [voidlinux/xbps#110]
Currently it is not possible with xbps to produce the same packages from the same source.

1.  `build-date` is different for every run of `xbps-create(1)` as it is set for the build time of the package. I think it's a bad idea to set the build-date staticly as that would be missleading.

  What side effects could be occur if we simply remove build-date? The build date is still coded in the mtime/ctime of the `.xbps` package.

2. Maybe there are some other issues such as the libarchive version that would produce different checksums in the resulting package.

**Comment by pullmoll** [comment]
Any C source which refers to the `__DATE__` macro in compiled code won't be reproducible either.

I also observed that large parts of the webkitgtk or webkit2gtk packages are always recompiled, even with ccache enabled, probably due to minor changes in the `DerivedSource/...` files, so those builds won't be reproducible.

I believe you will always have some non-reproducible packages, no matter how hard you try.

**Comment by dominikh** [comment]
Your issue doesn't say why having reproducible builds (in the context of Void packages) is a benefit and why we need it.

**Comment by Gottox** [comment]
@dominikh let me point that out:

We currently have two buildservers which independantly build their pachages (one for musl, one for glibc) They both create independant noarch packages.

If a xbps-src users uses both, musl and glibc with a shared hostdir the shasums fail for every noarch package if it is downloaded for glibc but your currently building musl and vice versa.

Further more @xtraeme mentioned multiple times, that reproducable builds are a nice thing to have. :)

**Comment by xtraeme** [comment]
@Gottox I agree with the `build-date` object removal, we can deduce the build date from the mtime of the xbps archive.

:+1:

**Comment by dominikh** [comment]
Does that mean that, for now, the issue can be reduced to noarch packages only? That'd avoid concerns such as mine (Go) or @pullmoll's (`__DATE__` macros and similar) to a large degree.

**Comment by Gottox** [comment]
The worst case scenario with Go is, that the build will take longer. The worst case with @pullmoll's date concern is that the build won't be reproducable for some packages.

Nevertheless, removing `build-date` won't have any of this side effects. Both issues described above rather apply to changes in https://github.com/voidlinux/void-packages/issues/2295 than those in xbps.

**Comment by thypon** [comment]
@Gottox go build system get the last upstream version for dependencies + it compiles all of them statically. That means that if you have 100 deps the probability is high that tomorrow you have another binary even if you didn't change nothing in your code.

**Comment by Gottox** [comment]
@thypon thanks for that explaination.
