### ISSUE TITLE
xbps-pkgdb -a doesn't fixes the pkgdb

### ISSUE THREAD

**Issue by radare** [voidlinux/xbps#114]
I was expecting that `xbps-pkgdb -a` do something like `xbps-pkgdb -a 2>&1 | cut -d : -f 1 >  pkgs; for a in $(cat pkgs) ; do sudo xbps-pkgdb $a ; done`.

Also, the current xbps-pkgdb -a output should be with -an. in order to not do anything.

(note

**Comment by xtraeme** [comment]
I'd like to see more details (debugging output), what you expected to fix, etc.

**Comment by xtraeme** [comment]
no feedback for 2 months, and no info provided
