### ISSUE TITLE
Cannot upgrade because of not enough free space

### ISSUE THREAD

**Issue by radare** [voidlinux/xbps#115]
I think one solution would be to allow `xbps-install` to remove the `/var/cache/xbps` directory after installing the package. The required disk space calculation should be changed, in order to expect only installedsizeOfAllpkgs + sizeofMaxpkgfile

**Comment by xtraeme** [comment]
Required disk space calculation collects required installed_size for all pkgs to be installed/upgraded/downloaded and then if pkg is already installed its current size is substracted.

Could you please provide more details in what's wrong? (hint you can use `-d` option to enable debugging) or `-n` for `dry-run` mode.

Thanks.

**Comment by xtraeme** [comment]
no feedback for 2 months, and no info provided
