### ISSUE TITLE
Package updates circumvent `replaces` check for virtual packages

### ISSUE THREAD

**Issue by dominikh** [voidlinux/xbps#116]
Trying to install both gawk and nawk, when gawk is already installed but of an older version, results in an update for gawk and an install for nawk:

```
$ xbps-install -n gawk nawk
gawk-4.1.3_3 update x86_64 http://repo.voidlinux.eu/current
nawk-20121220_1 install x86_64 http://repo.voidlinux.eu/current
```

(`-nd` output is at http://sprunge.us/HFSJ – not included here, as it's about 7000 lines long)

If gawk is already the latest version, installing nawk will remove gawk (the expected behaviour)

```
$ xbps-install -n gawk nawk
Package `gawk' already installed.
gawk-4.1.3_3 remove x86_64 http://repo.voidlinux.eu/current
nawk-20121220_1 install x86_64 http://repo.voidlinux.eu/current
```

**Comment by xtraeme** [comment]
Fixed for 0.48, thanks.
