### ISSUE TITLE
relative cachedir is handled wrong by xbps-install

### ISSUE THREAD

**Issue by nkoehring** [voidlinux/xbps#117]
When cachdir in xbps.conf is set to a relative path, xbps-install creates this path in the current working directory instead of handling it as rootdir+cachedir. The signature check on the other side handles it correctly and failes, because the downloaded package cannot be found. 

See [mailinglist](https://groups.google.com/forum/#!topic/voidlinux/MBthqLqWM0c) for further info of the original problem.

**Comment by xtraeme** [comment]
You are right, I've found the issue.

Will be fixed soon, thanks.

**Comment by xtraeme** [comment]
Meanwhile defaults are perfectly valid if you want `cachedir` relative to `rootdir`, i.e don't set anything in a configuration file and use `-r/--rootdir`, `cachedir` will be created at `rootdir/var/cache/xbps`.

**Comment by xtraeme** [comment]
FTR, relative cachedir is handled correctly via `-c/--cachedir`, the only issue is that after processing configuration files (`xbps.d(5)`), relative paths are not taken into account.
