### ISSUE TITLE
xbps outputs in every screen

### ISSUE THREAD

**Issue by maxmunzel** [voidlinux/xbps#123]
when using the 'screen' command to run a xbps command in the background, the 
```xbps-install: Installed `xyz` successfully (rootdir: /).``` -messages appears even when working in a different screen, interrupting heavily

**Comment by gregf** [comment]
Also had this issue recently during a install. Very annoying.

**Comment by Duncaen** [comment]
I'm not sure but maybe it happens if you dont have socklog installed but its activated in xbps.
``echo "syslog=false" > /etc/xbps.d/99-nolog.conf``

**Comment by chneukirchen** [comment]
I think xbps should drop LOG_CONS since the messages are printed to stderr anyway already.

**Comment by xtraeme** [comment]
@chneukirchen true, I'll drop LOG_CONS.
