### ISSUE TITLE
I upgraded xpbs and now I got broken dependencies

### ISSUE THREAD

**Issue by abelboldu** [voidlinux/xbps#124]
I upgraded xbps from an old version, and I got a broken env:

15:38:36 [root@gulik ~]# xbps-install xbps

Name    Action    Version           New version            Download size
libxbps update    0.43.1_5          0.47_4                 100KB 
xbps    update    0.43.1_5          0.47_4                 77KB 

Size to download:              178KB
Size required on disk:         218KB
Free space on disk:           4848MB

Do you want to continue? [YES/no] YES

[*] Downloading binary packages
libxbps-0.47_4.x86_64.xbps: 100KB [avg rate: 2778MB/s]
libxbps-0.47_4.x86_64.xbps.sig: 512B [avg rate: 17MB/s]
xbps-0.47_4.x86_64.xbps: 77KB [avg rate: 1019MB/s]
xbps-0.47_4.x86_64.xbps.sig: 512B [avg rate: 13MB/s]

[*] Verifying package integrity
libxbps-0.47_4: verifying RSA signature...
xbps-0.47_4: verifying RSA signature...

[*] Running transaction tasks
libxbps-0.43.1_5: updating to 0.47_4 ...
libxbps-0.47_4: unpacking ...
xbps-0.43.1_5: updating to 0.47_4 ...
xbps-0.47_4: unpacking ...

[*] Configuring unpacked packages
libxbps-0.47_4: configuring ...
libxbps-0.47_4: updated successfully.
xbps-0.47_4: configuring ...
xbps-0.47_4: updated successfully.

2 downloaded, 0 installed, 2 updated, 0 configured, 0 removed.
15:38:56 [root@gulik ~]# xbps-install -u
xbps-install: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by /usr/lib/libxbps.so.2)
15:38:59 [root@gulik ~]# xbps-install libxbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by xbps-query)
xbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by /usr/lib/libxbps.so.2)
xbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by xbps-query)
xbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by /usr/lib/libxbps.so.2)
cxbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by xbps-query)
xbps-query: /usr/lib/libc.so.6: version `GLIBC_2.22' not found (required by /usr/lib/libxbps.so.2)

How I can fix that?

**Comment by Duncaen** [comment]
Dont forget to sync the repo, if you use xbps-install you should use -S.

**Comment by xtraeme** [comment]
Use the xbps static binaries to upgrade:

http://repo.voidlinux.eu/static/

**Comment by abelboldu** [comment]
Thanks, it worked.

I used the static xbps-install, upgraded glibc and libressl and then I could upgrade whole system.

Loving this distro, keep up the good work
