### ISSUE TITLE
Suggestion: provide symbolic links with traditional names to new alternative packages (vi -> nvi, awk -> mawk, etc.)

### ISSUE THREAD

**Issue by suiginsoft** [voidlinux/xbps#128]
Just doing a fresh install and I was at a loss when I typed `vi` and got `command not found`. After searching through the file system and the package repository, decided to check your twitter feed as I noticed XBPS was just updated, thought maybe other stuff got changed, and saw you're switching to alternative packages for things like vi.

It would be nice if you still provided symbolic links with the traditional names to the new binaries, so our scripts don't break or people aren't forced to resort to substandard workarounds like using busybox's vi because they weren't aware of the new packages.

**Comment by xtraeme** [comment]
This is what xbps-alternatives(1) from 0.48 does.
