### ISSUE TITLE
Signing of armv7l repo issue.

### ISSUE THREAD

**Issue by Thotth** [voidlinux/xbps#137]
Hi!
I've tried to sign the repo full of *.xbps packs cross-built for the armv7l. Whole stuff is running  on the x86_64 machine.

When I've tried to make xbps-rindex -a ${REPO}/*.xbps  and facing the issue of "Incompatible architecture (armv7l)" // on the XBPS 0.47/0.48 // met complete silence with no action at all on the XBPS 0.50 // - it's just stalled right after the start.

As soon as xbps-packs were built by the xbps-src, the repo already contains ${ARCH}-repodata file: "armv7l-repodata" in my case. I've put that file in the ${REPO} folder on my ftp server and tried to sign only the packs contained in ${REPO}. All packs were "signed successfully" (xbps-rindex --sign ${REPO}; xbps-rindex --sign-pkg ${REPO}; said that). 

Next issue happens on the armv7l machine (using the local ftp server as the signed ${REPO} holder):
...
># xbps-install -Sy  \#successfully grabs repo content
># xbps-install mc \#mc - for example
...downloading packs
...verifying RCA signature
ERROR: libgpm-1.20.7_8: the RCA signature is not valid!
ERROR: libgpm-1.20.7_8: removed pkg archive and its signature.

This issue is permanent and I don't know how to be with that: XBPS/Void documentation doesn't spot this case so I'm stuck with the own XBPS repo, compiled but not working.

Any hope to make it works?

**Comment by xtraeme** [comment]
Unexisting issue... solution:

`XBPS_ARCH=armv7l xbps-rindex /path/to/repo/*.xbps`

**Comment by Thotth** [comment]
Thanks! Your solution partially helps.
> Is this solution some-kind mirrored in the Void/XBPS documentation? 
> Where is the '-a' param? Is it don't needed anymore? (XBPS 0.50 seems to requires it to be presented)

Anyway, how about second part of my question? Your solution solves only the half of mentioned issue, second one is still here after the signing the whole ${REPO}.

So, the question is: how the whole ${REPO} must be signed RIGHT WAY?
My current script looks like this:

>\#/bin/sh
>REPO=/home/ftp/binpkgs.armv7l
> \#generate the RCA key:
>openssl genrsa -des3 -out privkey.pem.base 4096
> \#cut the pass from the key due to signing of 6000++ packs:
>openssl rsa -in privkey.pem.base -out privkey.pem 
>
>\#remove all the previous signatures:
>rm -rf ${REPO}/*.sig 
> \#sign for repo:
>xbps-rindex --sign --signedby "13.0.2.16.16" --privkey privkey.pem  ${REPO}
>\# sign for packs:
>xbps-rindex --signedby "13.0.2.16.16" --privkey privkey.pem  --sign-pkg  ${REPO}/*.xbps 
> \# index repo
>XBPS_ARCH=armv7l xbps-rindex -a ${REPO}/*.xbps

This part works now without visible issues. 
But the "RCA signature is not valid!" error during package installation on the target armv7i is still exists! How it can be solved? I don't know. Am I done something wrong on the repo signing stage? 
Please spot the light on this issue too: how I must sign the void/xbps repo to use it on the remote machines in the network without any problems? Or what could bring to the mentioned RCA error on the target host?

**Comment by Duncaen** [comment]
@Thotth have you tried to use the --debug flag?
There are a lot of debug messages, see https://github.com/voidlinux/xbps/blob/master/lib/verifysig.c#L81

**Comment by Thotth** [comment]
@Duncaen yep, I've already tried it. "Bolt on 200" as saying it. I've digging the debug log and found that the another env_var must be set too: XBPS_TARGET_ARCH=armv7l. On the each stage of the repo signing. Moreover -  It does not helps. ARM machine still reports me about unsigned repository (thank you for the debug flag, it gave me more info about errors). And I'm there where I was - my repo is still unsigned for my arm machines.

**Comment by Thotth** [comment]
Someone! Why this issue is closed?! I can't force armv7l void/xbps repo to be signed on the foreign intel x86_64 platform! Is that "unexisting issue"?! Huh... 

I can't make the void/xbps repo signed! How many times I must write that to be listened?! 

Guys, give me a working recipe, please. How you are doing that on your repos? - An example, a script, something that just works, something that solves this issue. 

And YES, this is an issue, folks. And it must be solved.
Sorry for the tone, but it seems that this issue just ignored. Or this issue has no solution.

**Comment by Duncaen** [comment]
@Thotth can you post the log of xbps-install on your target machine, with the debug flag?

**Comment by xtraeme** [comment]
I told you the solution before, you need to set the XBPS_TARGET_ARCH for
all xbps commands.

**Comment by Thotth** [comment]
@xtraeme the XBPS_ARCH is little differ from the XBPS_TARGET_ARCH, isn't it? "The solution" does not solves this issue, no matter what you say.
@Duncaen of cause. Complete? Partial? May be only the integrity check part? [debug] said me about the "unsigned repository", so I think that this is signing process issue - I can grab its log and post it here, skipping the list of packs. Which one must be attached?

**Comment by xtraeme** [comment]
For `xbps-rindex(1)` both env vars have the same effect `XBPS_ARCH` or `XBPS_TARGET_ARCH`.

As I said previously you need to set the env var for all `xbps-rindex(1)` commands:

```
$ XBPS_ARCH=armv7l xbps-rindex --sign ... /repo
$ XBPS_ARCH=armv7l xbps-rindex --sign-pkg /repo/*.xbps
```

In fact you'll have to set this env var for all xbps commands if you want to force another architecture.

`apropos xbps` is your friend.

**Comment by Thotth** [comment]
OK, issue is still exists. And it seems that I localized it: I've renamed armv7-repodata to the .tar.xz and unpack this archive to be sure that the repo is signed. It is signed. But xbps-install still said me that the repo is unsigned, so the "bug" is somewhere on the "client side". Keep digging...
