### ISSUE TITLE
Robustness against division by 0 in xbps_array_foreach_cb_multi

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/xbps#140]
Due to a Kernel bug (fixed in 4.2, patch at https://patchwork.linux-mips.org/patch/10740/), Linux reports on MIPS that it runs on 0 cores... which results in a divison by zero in xbps_array_foreach_cb_multi when computing slices: `slicecount = arraycount / maxthreads;`

Let's just assume we have 1 core when the sysconf returns 0.

Perhaps `maxthreads <= 1` is even clearer.

```diff
--- lib/plist.c.orig
+++ lib/plist.c
@@ -101,7 +101,7 @@
                return 0;

        maxthreads = (int)sysconf(_SC_NPROCESSORS_ONLN);
-       if (maxthreads < 0 || maxthreads == 1) /* use single threaded routine */  
+       if (maxthreads <= 0 || maxthreads == 1) /* use single threaded routine */
                return xbps_array_foreach_cb(xhp, array, dict, fn, arg);  

        thd = calloc(maxthreads, sizeof(*thd));  
```

**Comment by Gottox** [comment]
Wasn't this already fixed by: https://github.com/voidlinux/xbps/commit/a9482027b20f72ec361e38155b89038a82196a7f

**Comment by chneukirchen** [comment]
True, I didn't pull.
