### ISSUE TITLE
xbps-install fails with unsigned packages in remote repo.

### ISSUE THREAD

**Issue by yopito** [voidlinux/xbps#141]
Just created a (private) repository available via HTTP that contains **unsigned** packages.
tests with `xbps-query` are fine with this repo.
But `xbps-install` fails to use this repository: 
```
# xbps-install -S -y --repo=http://mataru.maison/voidlinux/repo.mine/saltstack salt-core
1 package will be installed:

  salt-core-2015.8.3_1

Size required on disk:          12MB
Free space on disk:           9530MB

[*] Downloading binary packages
ERROR: [trans] failed to download `salt-core-2015.8.3_1' signature from \
    `http://mataru.maison/voidlinux/repo.mine/saltstack': Not Found
```
ngnix `access.log` file shows a tentative to retrieve the corresponding .sig file and return a HTTP 404 error code since it does not exist:
```
192.168.69.63 - - [23/Dec/2015:18:06:19 +0100] \
    "GET /voidlinux/repo.mine/saltstack/salt-core-2015.8.3_1.noarch.xbps.sig \
    HTTP/1.1" 404 3652 "-" "xbps/2.0" "-"
```
repo index files(s) ([arch]-repodata files) are fine: If I copy the repo locally (on disk) and perform the installation without any modification (no repodata generation in particular), everything is fine:
```
# xbps-install -S -y --repo=/root/saltstack salt-core
1 package will be installed:

  salt-core-2015.8.3_1

Size required on disk:          12MB
Free space on disk:           9530MB

[*] Downloading binary packages

[*] verifying package integrity
[*] running transaction task
...
```

Other info:
- my private repo contains only non-existent packages in official repos (`salt-*`)
- rechecked several times my options and perform various tests 
- `xbps-query -S -Lv` on my repo indicates "(RSA unsigned)" as expected
- [arch]-metada files have been generated with xbps-install version 0.51 static on a CentOS 7

... So I'm a little lost. did I missed something obvious ? 
Does xbps-install does not handle HTTP 404 correctly or the non-existence of .sig file  ? 
does the metadata files has incorrect info that prevent its use from HTTP repo ?

**Comment by Duncaen** [comment]
Remote repos should be signed, end.

**Comment by yopito** [comment]
you mean **must** be signed ?
a little annoying
And  the documentation *should* mention it ...

**Comment by Duncaen** [comment]
```
   Starting from now on all remote repositories must be signed and verified.
   Local repos do not need to be signed and they will work as before.
```

**Comment by Gottox** [comment]
@yopito Actually that's a security feature. But you're right about the fact, that it needs to be documented.

**Comment by yopito** [comment]
OK, thanks for your returns and the update of the documentation.
