### ISSUE TITLE
xbps-uchroot fails if chrootdir is on a shared mount

### ISSUE THREAD

**Issue by ebfe** [voidlinux/xbps#152]
To reproduce

```
# findmnt -o PROPAGATION -n $(stat -c '%m' .)
private
# mount --make-shared $(stat -c '%m' .)
# findmnt -o PROPAGATION -n $(stat -c '%m' .)
shared

# mkdir -p chroot/{proc,sys,dev}
# xbps-uchroot ${PWD}/chroot bla
ERROR: Failed to move /home/x/chroot as rootfs (Invalid argument)
```

Leaving behind hard to clean up mounts in chroot.

The problem is that 

```
main.c:353                  if (mount(chrootdir, "/", NULL, MS_MOVE, NULL) == -1)
```

fails if chrootdir is on a shared mount.

People trying to use void-mklive on a systemd based system (which seems to
`mount --make-shared` everything by default) have a bad time.

**Comment by chneukirchen** [comment]
I noticed the same error when `/` is not a mount point (e.g. because you are in a chroot).

Doing a `mount --rbind /chroot /chroot` on the host fixed that.

**Comment by xtraeme** [comment]
@ebfe hopefully this should be enough? just continue even if MS_MOVE fails.

I tested this with @chneukirchen case. Sorry but I do not have any system with systemd.

**Comment by ebfe** [comment]
> @ebfe hopefully this should be enough? just continue even if MS_MOVE fails.
Can't reach my arch test box right now. Will try it next week.

**Comment by ebfe** [comment]
> I tested this with @chneukirchen case. Sorry but I do not have any system with systemd.

Ah, actually you don't need systemd to reproduce, see initial comment
for steps to reproduce.

**Comment by ebfe** [comment]
At 5117ff84a2660bdc43036b59b463571604e63a05 it no longer errors, but still doesn't clean up mounts in the chrootdir.
