### ISSUE TITLE
Prevent a package upgrade: not with "conflicts" directive ?

### ISSUE THREAD

**Issue by yopito** [voidlinux/xbps#153]
I have `burp-client-1.4.40_2` package installed. 

While packaging ` burp-client-2.0.34` , need to prevent updates from 1.x to 2.x : force operator to install from scratch only. 
So I've added this into its template file: " `conflicts="burp-client<2.0"`  "
But it does not work.

Because updating process removes burp-client-1.4.40  **before** installing burp-2.0.x ?

This behaviour might be a `conflicts` directive handling bug, that should be evaluated before anything ? Or do I have to try other ways to achieve it ?

I see these as possible workarounds:
* check this case into an `INSTALL` script (in `pre` section for `$ACTION` value)  to detect the old package ?
* creating a new package with a different name (like `burp2-client`) ?

NB: no other case found in xbps-src tree like this : using `<` in `conflicts` and reference the same package in its `conflicts` .

**Comment by chneukirchen** [comment]
This is behavior is not possible.  You can create a second package (and make it conflict if it actually does.)

**Comment by yopito** [comment]
OK, thanks for your reply. 
Don't know if this issue might be usefull or not, so I do not close it.
