### ISSUE TITLE
xbps-install: segfault with packages on hold

### ISSUE THREAD

**Issue by lemmi** [voidlinux/xbps#161]
I was switching over to amd opensource drivers. As catalyst needs xserver in version 1.17, all related packages were on hold.

> xbps-query -H
> xf86-input-evdev-2.10.0_2
> xorg-server-1.17.4_2

I removed catalyst, installed libGL and after that the opensource drivers with:

> xbps-install xf86-video-{amdgpu,ati}

Debug output and backtrace is here:
https://gist.github.com/anonymous/61bbb620cc107ea92952f5fc03781e96

**Comment by xtraeme** [comment]
This has been fixed for 0.52, which has not been released yet.

Please wait until it's released, thanks

**Comment by lemmi** [comment]
No problem, i just stumbled over that and wanted to report. I could work easily around that, so if it's fixed, you can close that issue, too.

**Comment by xtraeme** [comment]
Fixed in 0.52, thanks.
