### ISSUE TITLE
xbps-remove : no dry run on obsolete packages removal

### ISSUE THREAD

**Issue by yopito** [voidlinux/xbps#165]
hello,
option `-n` does not work, at least with `-O` : obsolete packages are removed.
```
$ sudo xbps-remove --version
XBPS: 0.51 API: 20151030 GIT: UNSET
```
```
$ sudo xbps-remove -n -O
Removed python-setuptools-20.6.7_1.noarch.xbps from cachedir (obsolete)
Removed python-urllib3-1.15_1.noarch.xbps from cachedir (obsolete)
[...]
```
on 2nd invocation, nothing found, so removal has really been done:
```
$ sudo xbps-remove -n -O
(nothing)
```

**Comment by jantatje** [comment]
xbps_transaction_autoremove_pkgs() doesn't take a dry-run argument, thus xbps-remove can't pass it. It should either abort and report that -O doesn't support -n or dry-run has to be implemented for xbps_transaction_autoremove_pkgs(). I will work on this.
