### ISSUE TITLE
xbps-alternatives: clean up old links when switching alternatives

### ISSUE THREAD

**Issue by leahneukirchen** [voidlinux/xbps#166]
If we have alternatives that do not consist of exactly the same files (e.g. because one package has manpages and another one doesn't), changing the alternative keeps the links pointing to the old destination.

Instead, xbps-alternatives should remove all links first, and then create the new ones.

**Comment by Gottox** [comment]
treating the alternatives links as normal files of a package could reduce code duplication here. This would also allow to search for the owning package with xbps-query -o.
