### ISSUE TITLE
BUG: xbps-query -Ro "*/X11*" crashes

### ISSUE THREAD

**Issue by ultimatesolution** [voidlinux/xbps#167]
Environment:
$ lsb_release -a
LSB Version:	1.0
Distributor ID:	VoidLinux
Description:	Void Linux
Release:	rolling
Codename:	void
[user@vnote bochs]$ uname -a
Linux vnote 4.5.1_1 #1 SMP PREEMPT Wed Apr 13 02:54:58 UTC 2016 x86_64 GNU/Linux
[user@vnote bochs]$ xbps-query --version
XBPS: 0.51 API: 20151030 GIT: UNSET

This command cashes xpbs-query:
$ xbps-query -Ro "*/X11*"
*** Error in `xbps-query': double free or corruption (fasttop): 0x00007fe3d8030a00 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x6ebe5)[0x7fe3e7883be5]
/usr/lib/libc.so.6(+0x74486)[0x7fe3e7889486]
/usr/lib/libc.so.6(+0x74c6e)[0x7fe3e7889c6e]
/usr/lib/libcrypto.so.37(OBJ_NAME_add+0x7c)[0x7fe3e6e3ed2c]
/usr/lib/libssl.so.38(SSL_library_init+0x1c1)[0x7fe3e75eb571]
/usr/lib/libxbps.so.2(+0xbc5d)[0x7fe3e7bc2c5d]
/usr/lib/libxbps.so.2(+0x139df)[0x7fe3e7bca9df]
/usr/lib/libxbps.so.2(+0x2d97e)[0x7fe3e7be497e]
/usr/lib/libarchive.so.13(archive_read_open1+0x76)[0x7fe3e712af66]
/usr/lib/libxbps.so.2(+0x2da6a)[0x7fe3e7be4a6a]
/usr/lib/libxbps.so.2(xbps_archive_fetch_file+0x32)[0x7fe3e7be4ad2]
/usr/lib/libxbps.so.2(xbps_archive_fetch_plist+0xb)[0x7fe3e7be4e9b]
xbps-query(+0x4242)[0x5645af08d242]
/usr/lib/libxbps.so.2(+0x2bba9)[0x7fe3e7be2ba9]
/usr/lib/libpthread.so.0(+0x73f4)[0x7fe3e7e053f4]
/usr/lib/libc.so.6(clone+0x6d)[0x7fe3e78fcbad]
======= Memory map: ========
5645af089000-5645af090000 r-xp 00000000 08:1d 663581                     /usr/bin/xbps-query
5645af290000-5645af291000 r--p 00007000 08:1d 663581                     /usr/bin/xbps-query
5645af291000-5645af292000 rw-p 00008000 08:1d 663581                     /usr/bin/xbps-query
5645b0c1d000-5645b12ba000 rw-p 00000000 00:00 0                          [heap]
7fe3d0000000-7fe3d0876000 rw-p 00000000 00:00 0 
7fe3d0876000-7fe3d4000000 ---p 00000000 00:00 0 
7fe3d4000000-7fe3d4857000 rw-p 00000000 00:00 0 
7fe3d4857000-7fe3d8000000 ---p 00000000 00:00 0 
7fe3d8000000-7fe3d8856000 rw-p 00000000 00:00 0 
7fe3d8856000-7fe3dc000000 ---p 00000000 00:00 0 
7fe3dfdea000-7fe3dfe00000 r-xp 00000000 08:1d 664982                     /usr/lib/libgcc_s.so.1
7fe3dfe00000-7fe3dffff000 ---p 00016000 08:1d 664982                     /usr/lib/libgcc_s.so.1
7fe3dffff000-7fe3e0000000 rw-p 00015000 08:1d 664982                     /usr/lib/libgcc_s.so.1
7fe3e0000000-7fe3e0868000 rw-p 00000000 00:00 0 
7fe3e0868000-7fe3e4000000 ---p 00000000 00:00 0 
7fe3e40c4000-7fe3e40d7000 r-xp 00000000 08:1d 664644                     /usr/lib/libresolv-2.23.so
7fe3e40d7000-7fe3e42d7000 ---p 00013000 08:1d 664644                     /usr/lib/libresolv-2.23.so
7fe3e42d7000-7fe3e42d8000 r--p 00013000 08:1d 664644                     /usr/lib/libresolv-2.23.so
7fe3e42d8000-7fe3e42d9000 rw-p 00014000 08:1d 664644                     /usr/lib/libresolv-2.23.so
7fe3e42d9000-7fe3e42db000 rw-p 00000000 00:00 0 
7fe3e42db000-7fe3e42e0000 r-xp 00000000 08:1d 664932                     /usr/lib/libnss_dns-2.23.so
7fe3e42e0000-7fe3e44df000 ---p 00005000 08:1d 664932                     /usr/lib/libnss_dns-2.23.so
7fe3e44df000-7fe3e44e0000 r--p 00004000 08:1d 664932                     /usr/lib/libnss_dns-2.23.so
7fe3e44e0000-7fe3e44e1000 rw-p 00005000 08:1d 664932                     /usr/lib/libnss_dns-2.23.so
7fe3e44e1000-7fe3e44ec000 r-xp 00000000 08:1d 664947                     /usr/lib/libnss_files-2.23.so
7fe3e44ec000-7fe3e46eb000 ---p 0000b000 08:1d 664947                     /usr/lib/libnss_files-2.23.so
7fe3e46eb000-7fe3e46ec000 r--p 0000a000 08:1d 664947                     /usr/lib/libnss_files-2.23.so
7fe3e46ec000-7fe3e46ed000 rw-p 0000b000 08:1d 664947                     /usr/lib/libnss_files-2.23.so
7fe3e46ed000-7fe3e46f3000 rw-p 00000000 00:00 0 
7fe3e46f3000-7fe3e46f4000 ---p 00000000 00:00 0 
7fe3e46f4000-7fe3e4ef4000 rw-p 00000000 00:00 0 
7fe3e4ef4000-7fe3e4ef5000 ---p 00000000 00:00 0 
7fe3e4ef5000-7fe3e56f5000 rw-p 00000000 00:00 0 
7fe3e56f5000-7fe3e56f6000 ---p 00000000 00:00 0 
7fe3e56f6000-7fe3e5ef6000 rw-p 00000000 00:00 0 
7fe3e5ef6000-7fe3e5ef7000 ---p 00000000 00:00 0 
7fe3e5ef7000-7fe3e66f7000 rw-p 00000000 00:00 0 
7fe3e66f7000-7fe3e6706000 r-xp 00000000 08:1d 665072                     /usr/lib/libbz2.so.1.0.6
7fe3e6706000-7fe3e6905000 ---p 0000f000 08:1d 665072                     /usr/lib/libbz2.so.1.0.6
7fe3e6905000-7fe3e6907000 rw-p 0000e000 08:1d 665072                     /usr/lib/libbz2.so.1.0.6
7fe3e6907000-7fe3e692c000 r-xp 00000000 08:1d 665039                     /usr/lib/liblzma.so.5.2.2
7fe3e692c000-7fe3e6b2b000 ---p 00025000 08:1d 665039                     /usr/lib/liblzma.so.5.2.2
7fe3e6b2b000-7fe3e6b2c000 r--p 00024000 08:1d 665039                     /usr/lib/liblzma.so.5.2.2
7fe3e6b2c000-7fe3e6b2d000 rw-p 00025000 08:1d 665039                     /usr/lib/liblzma.so.5.2.2
7fe3e6b2d000-7fe3e6b31000 r-xp 00000000 08:1d 664974                     /usr/lib/libattr.so.1.1.0
7fe3e6b31000-7fe3e6d30000 ---p 00004000 08:1d 664974                     /usr/lib/libattr.so.1.1.0
7fe3e6d30000-7fe3e6d31000 r--p 00003000 08:1d 664974                     /usr/lib/libattr.so.1.1.0
7fe3e6d31000-7fe3e6d32000 rw-p 00004000 08:1d 664974                     /usr/lib/libattr.so.1.1.0
7fe3e6d32000-7fe3e6ee0000 r-xp 00000000 08:1d 663077                     /usr/lib/libcrypto.so.37.0.0
7fe3e6ee0000-7fe3e70e0000 ---p 001ae000 08:1d 663077                     /usr/lib/libcrypto.so.37.0.0
7fe3e70e0000-7fe3e7100000 r--p 001ae000 08:1d 663077                     /usr/lib/libcrypto.so.37.0.0
7fe3e7100000-7fe3e710a000 rw-p 001ce000 08:1d 663077                     /usr/lib/libcrypto.so.37.0.0
7fe3e710a000-7fe3e710e000 rw-p 00000000 00:00 0 
7fe3e710e000-7fe3e71a2000 r-xp 00000000 08:1d 669084                     /usr/lib/libarchive.so.13.1.2
7fe3e71a2000-7fe3e73a1000 ---p 00094000 08:1d 669084                     /usr/lib/libarchive.so.13.1.2
7fe3e73a1000-7fe3e73a4000 r--p 00093000 08:1d 669084                     /usr/lib/libarchive.so.13.1.2
7fe3e73a4000-7fe3e73a5000 rw-p 00096000 08:1d 669084                     /usr/lib/libarchive.so.13.1.2
7fe3e73a5000-7fe3e73a6000 rw-p 00000000 00:00 0 
7fe3e73a6000-7fe3e73bb000 r-xp 00000000 08:1d 664991                     /usr/lib/libz.so.1.2.8
7fe3e73bb000-7fe3e75ba000 ---p 00015000 08:1d 664991                     /usr/lib/libz.so.1.2.8
7fe3e75ba000-7fe3e75bb000 rw-p 00014000 08:1d 664991                     /usr/lib/libz.so.1.2.8
7fe3e75bb000-7fe3e760c000 r-xp 00000000 08:1d 667620                     /usr/lib/libssl.so.38.0.0
7fe3e760c000-7fe3e780c000 ---p 00051000 08:1d 667620                     /usr/lib/libssl.so.38.0.0
7fe3e780c000-7fe3e7810000 r--p 00051000 08:1d 667620                     /usr/lib/libssl.so.38.0.0
7fe3e7810000-7fe3e7815000 rw-p 00055000 08:1d 667620                     /usr/lib/libssl.so.38.0.0
7fe3e7815000-7fe3e79ad000 r-xp 00000000 08:1d 664639                     /usr/lib/libc-2.23.so
7fe3e79ad000-7fe3e7bad000 ---p 00198000 08:1d 664639                     /usr/lib/libc-2.23.so
7fe3e7bad000-7fe3e7bb1000 r--p 00198000 08:1d 664639                     /usr/lib/libc-2.23.so
7fe3e7bb1000-7fe3e7bb3000 rw-p 0019c000 08:1d 664639                     /usr/lib/libc-2.23.so
7fe3e7bb3000-7fe3e7bb7000 rw-p 00000000 00:00 0 
7fe3e7bb7000-7fe3e7bfc000 r-xp 00000000 08:1d 667621                     /usr/lib/libxbps.so.2.0.0
7fe3e7bfc000-7fe3e7dfb000 ---p 00045000 08:1d 667621                     /usr/lib/libxbps.so.2.0.0
7fe3e7dfb000-7fe3e7dfd000 r--p 00044000 08:1d 667621                     /usr/lib/libxbps.so.2.0.0
7fe3e7dfd000-7fe3e7dfe000 rw-p 00046000 08:1d 667621                     /usr/lib/libxbps.so.2.0.0
7fe3e7dfe000-7fe3e7e16000 r-xp 00000000 08:1d 664669                     /usr/lib/libpthread-2.23.so
7fe3e7e16000-7fe3e8015000 ---p 00018000 08:1d 664669                     /usr/lib/libpthread-2.23.so
7fe3e8015000-7fe3e8016000 r--p 00017000 08:1d 664669                     /usr/lib/libpthread-2.23.so
7fe3e8016000-7fe3e8017000 rw-p 00018000 08:1d 664669                     /usr/lib/libpthread-2.23.so
7fe3e8017000-7fe3e801b000 rw-p 00000000 00:00 0 
7fe3e801b000-7fe3e803e000 r-xp 00000000 08:1d 664667                     /usr/lib/ld-2.23.so
7fe3e8228000-7fe3e822f000 rw-p 00000000 00:00 0 
7fe3e823a000-7fe3e823d000 rw-p 00000000 00:00 0 
7fe3e823d000-7fe3e823e000 r--p 00022000 08:1d 664667                     /usr/lib/ld-2.23.so
7fe3e823e000-7fe3e823f000 rw-p 00023000 08:1d 664667                     /usr/lib/ld-2.23.so
7fe3e823f000-7fe3e8240000 rw-p 00000000 00:00 0 
7ffff9ca7000-7ffff9cc8000 rw-p 00000000 00:00 0                          [stack]
7ffff9dbf000-7ffff9dc2000 r--p 00000000 00:00 0                          [vvar]
7ffff9dc2000-7ffff9dc4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

Zipped core dump:

[core_xbps-query.26640.zip](https://github.com/voidlinux/xbps/files/231336/core_xbps-query.26640.zip)

**Comment by ebfe** [comment]
#0  0x00007f417d7e6207 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
    #1  0x00007f417d7e768a in __GI_abort () at abort.c:89
    #2  0x00007f417d821bea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7f417d91bf68 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
    #3  0x00007f417d827486 in malloc_printerr (action=3, str=0x7f417d91c0c0 "double free or corruption (fasttop)", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5007
    #4  0x00007f417d827c6e in _int_free (av=0x7f4164000020, p=<optimized out>, have_lock=0) at malloc.c:3868
    #5  0x00007f417cddcd2c in OBJ_NAME_add () from /usr/lib/libcrypto.so.37
    #6  0x00007f417cdc8e65 in EVP_add_cipher () from /usr/lib/libcrypto.so.37
    #7  0x00007f417d5893ce in SSL_library_init () from /usr/lib/libssl.so.38
    #8  0x00007f417db60c5d in fetch_ssl (conn=conn@entry=0x7f416c009990, URL=URL@entry=0x7f416c00a6e0, verbose=verbose@entry=0) at fetch/common.c:947
    #9  0x00007f417db689df in http_connect (cached=<synthetic pointer>, flags=0x0, purl=0x0, URL=0x7f416c00a6e0) at fetch/http.c:745
    #10 http_request (URL=0x7f416c00a6e0, op=<optimized out>, op@entry=0x7f417db8a398 "GET", us=us@entry=0x0, purl=0x0, flags=flags@entry=0x0) at fetch/http.c:875
    #11 0x00007f417db68d99 in fetchXGetHTTP (URL=<optimized out>, us=us@entry=0x0, flags=flags@entry=0x0) at fetch/http.c:1244
    #12 0x00007f417db62a18 in fetchXGet (flags=0x0, us=0x0, URL=<optimized out>) at fetch/fetch.c:88
    #13 fetchGet (URL=<optimized out>, flags=flags@entry=0x0) at fetch/fetch.c:102
    #14 0x00007f417db8297e in fetch_archive_open (a=<optimized out>, client_data=0x7f416c000aa0) at plist_fetch.c:53
    #15 0x00007f417d0c8f66 in archive_read_open1 () from /usr/lib/libarchive.so.13
    #16 0x00007f417db82a6a in open_archive_by_url (url=0x7f416c00a6e0) at plist_fetch.c:103
    #17 open_archive (url=<optimized out>) at plist_fetch.c:137
    #18 0x00007f417db82ad2 in xbps_archive_fetch_file (url=url@entry=0x7f416c000aa0 "https://repo.voidlinux.eu/current/gstreamer-devel-0.10.36_8.x86_64.xbps", fname=fname@entry=0x558230b9c017 "/files.plist") at plist_fetch.c:153
    #19 0x00007f417db82e9b in xbps_archive_fetch_plist (url=url@entry=0x7f416c000aa0 "https://repo.voidlinux.eu/current/gstreamer-devel-0.10.36_8.x86_64.xbps", plistf=plistf@entry=0x558230b9c017 "/files.plist")
        at plist_fetch.c:263
    #20 0x0000558230b9a242 in repo_match_cb (xhp=0x7ffd55acd1c0, obj=0x558231bb2040, key=<optimized out>, arg=0x7ffd55accd80, done=<optimized out>) at ownedby.c:145
    #21 0x00007f417db80ba9 in array_foreach_thread (arg=0x55823287d1b8) at plist.c:76
    #22 0x00007f417dda33f4 in start_thread (arg=0x7f417be93700) at pthread_create.c:333
    #23 0x00007f417d89abad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by ebfe** [comment]
SSL_library_init is called multiple times/concurrent with other threads already using ssl. Needs some locking.
