### ISSUE TITLE
xbps-install: Mistakes Transmeta Crusoe for i586

### ISSUE THREAD

**Issue by kazblox** [voidlinux/xbps#175]
Even though the Transmeta Crusoe does lack nopl, requiring it to be a full i686, the Linux kernel has emulated this function. But, xbps-install treats the CPU as i586, which causes problems, mainly downloading the repodata from the main Void Linux xbps repositories, as it tries to download "i586-repodata" instead of "i686-repodata".

This renders my earlier Lifebook P model unable to uninstall any packages.

**Comment by ebfe** [comment]
`echo architecture=i686 | sudo tee /etc/xbps.d/arch.conf` might help.

**Comment by kazblox** [comment]
Thanks! That solved the problem.
