### ISSUE TITLE
Packages up to date should not be an error

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/xbps#194]
For automation, it's useful to write `xbps-install -Su pkg1 pkg2 pkg3` to ensure the three packages are at the newest version.

This should not fail if any package is up to date already.

Also `xbps-install -S pkg1 pkg2 pkg3` should not fail when all packages are installed imo.

**Comment by Gottox** [comment]
Not sure about the `xbps-install -S pkg1 pkg2 pkg3` issue.
