### ISSUE TITLE
xbps-uchroot: tries to interpret options in cmdargs as its own

### ISSUE THREAD

**Issue by ackalker** [voidlinux/xbps#203]
``` sh
$ xbps-query -p pkgver xbps
xbps-0.51_10
```

According to:

```
Usage: xbps-uchroot [-b src:dest] [-O -t -o <opts>] <dir> <cmd> [<cmdargs>]
```

I should be able to pass arguments to a command without quoting, etc.
However, it appears that `xbps-uchroot` interprets (and rejects) at least some flags meant for a command as being meant for `xbps-uchroot` itself.

Steps to reproduce:

With a prepared chroot environment in `mnt`, say Void Linux itself, run:

``` sh
$ sudo xbps-uchroot mnt /usr/bin/xbps-install -y extlinux
xbps-uchroot: invalid option -- 'y'
```

**Comment by ackalker** [comment]
I have a hunch (haven't looked at the source code for `xbps-uchroot` yet) that this may be related to `getopt(3)`, and I've read that there is a [difference between musl libc and GNU libc](http://wiki.musl-libc.org/wiki/Functional_differences_from_glibc#Miscellaneous_functions_with_GNU_quirks) in that regard. Maybe this helps.
The behaviour is seen with:

```sh
$ ldd /usr/bin/xbps-query|grep libc.so
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f843a997000)
```
so I believe that means GNU libc.

**Comment by Duncaen** [comment]
use `--` to stop the option parsing, e.g. `xbps-uchroot /mnt xbps-install -- -Sy base-system`.

**Comment by ackalker** [comment]
@Duncaen Thanks for the tip. Would it be possible to add this to the usage message?

Something line:
```
Usage: xbps-uchroot [-b src:dest] [-O -t -o <opts>] <dir> [--] <cmd> [<cmdargs>]
```
This could be of some help to people not used to this convention. For instance, Arch Linux's `arch-chroot` does *not* support `--` to separate command and cmdargs from its own options.

**Comment by Duncaen** [comment]
Yes I think that would be a good addition, though this is glibc specific, I think musl just stopes parsing at the first option it doesn't know about.
glibc can do this if the `POSIXLY_CORRECT` environment variable is set or a `+` is prefixed to the optstring argument of `getopt(3)`.
Archs `arch-chroot` which is just a bash wrapper around `chroot(1)` should support this too.

**Comment by ackalker** [comment]
Ah, thanks again. Maintaining tools which could be linked to either musl libc and glibc must be quite a challenge :smile:
