### ISSUE TITLE
xbps-install: After install of base-system to directory for chroot and enter the chroot, `xbps-query -l` shows no output, unable to install more packages

### ISSUE THREAD

**Issue by ackalker** [voidlinux/xbps#205]
Host: Arch Linux x86_64 (multilib)
Host XBPS: xbps-git 0.51.r130.g7d06fb0-1 (built from PKGBUILD in the AUR)

After I used `xbps-install` to install `base-system` to a directory for chroot, when I entered the chroot using `arch-chroot`, `xbps-query -l` produced no output. When I tried to install an extra package, `syslinux`, in the chroot, package installation failed with `Unable to locate 'syslinux' in repository pool.`

I was able to work around this (get a list of installed packages and install more packages) by entering the chroot and forcing a reinstall of `base-system`.

Steps to reproduce are in this script (which i named `repro-archlinux.sh`:
```bash
#!/bin/bash

set -x

[[ -d mnt ]] || mkdir mnt
dd if=/dev/zero of=repro-archlinux.img bs=1 count=0 seek=1G
mke2fs -F -L Void -t ext2 repro-archlinux.img
sudo mount repro-archlinux.img mnt
sudo xbps-install -Syd -R https://repo.voidlinux.eu/current -r mnt base-system
sudo touch mnt/etc/resolv.conf
sudo arch-chroot $(pwd)/mnt xbps-query -l
sudo arch-chroot $(pwd)/mnt xbps-install -y syslinux
sudo arch-chroot $(pwd)/mnt xbps-query -l
sudo arch-chroot $(pwd)/mnt xbps-install -Syd -ff base-system
sudo arch-chroot $(pwd)/mnt xbps-query -l
sudo arch-chroot $(pwd)/mnt xbps-install -y -ff syslinux
sudo arch-chroot $(pwd)/mnt xbps-query -l
sudo umount mnt
```

Output of running this on my host system is [here](https://gist.github.com/cec53818939fe9198a845a5f7cf05451).

I was unable to reproduce this in a VM runnins a freshly installed Void Linux, using this script which I named `repro-voidlinux.sh`:

```
#!/bin/bash

set -x

[[ -d mnt ]] || mkdir mnt
dd if=/dev/zero of=repro-voidlinux.img bs=1 count=0 seek=1G
mke2fs -F -L Void -t ext2 repro-voidlinux.img
sudo mount repro-voidlinux.img mnt
sudo xbps-install -Syd -R https://repo.voidlinux.eu/current -r mnt base-system
sudo cp /etc/resolv.conf mnt/etc/
sudo xbps-uchroot $(pwd)/mnt -- xbps-query -l
sudo xbps-uchroot $(pwd)/mnt -- xbps-install -y syslinux
sudo xbps-uchroot $(pwd)/mnt -- xbps-query -l
sudo xbps-uchroot $(pwd)/mnt -- xbps-install -Syd -ff base-system
sudo xbps-uchroot $(pwd)/mnt -- xbps-query -l
sudo xbps-uchroot $(pwd)/mnt -- xbps-install -y -ff syslinux
sudo xbps-uchroot $(pwd)/mnt -- xbps-query -l
sudo umount mnt
```

Output of running the above script in my VM is [here](https://gist.github.com/049af7c5150b663c5bbea17580b4bc72).

Perhaps my inability to reproduce this on Void Linux could be due to `xbps-install` accidentally picking up files from outside the chroot (which in the VM is Void Linux itself), but I haven't found clues of this in the debug output. Perhaps it is an idea to run it using `strace -e file` and check for any file accesses which are outside of `mnt`?

**Comment by Duncaen** [comment]
The failing `xbps-query -l` and `xbps-install -y` would be interesting with `-d`.

**Comment by ackalker** [comment]
@Duncaen Thanks, I will upload new logs asap.

**Comment by ackalker** [comment]
@Duncaen Logs with more debug info, [on host](https://gist.github.com/60c0005471cc62983c78867ece1fa0b2) and [in VM](https://gist.github.com/52dc6f2cfac7711dd170c919941b0910)

**Comment by ackalker** [comment]
Hmm,
```diff
-+ sudo arch-chroot /home/miki/proj/qemu/archlinux/mnt xbps-install -yd syslinux
++ sudo xbps-uchroot /home/miki/mnt -- xbps-install -yd syslinux
[..snip..]
-[DEBUG] [repo] `//var/db/xbps/https___repo_voidlinux_eu_current/x86_64-repodata' 
-[DEBUG] [repo] `//var/db/xbps/https___repo_voidlinux_eu_current/x86_64-repodata' 
-Unable to locate 'syslinux' in repository pool.
```
Maybe `xbps-install` forgets to store repodata *in the chroot dir* when used with `-r` option? Just a guess...

**Comment by Duncaen** [comment]
Archlinux:
````
[DEBUG] metadir=/home/miki/proj/qemu/archlinux/mnt//var/lib/xbps/db/xbps
````
Void Linux:
````
[DEBUG] metadir=/home/miki/mnt//var/db/xbps
````
And inside the chroot:
````
[DEBUG] metadir=//var/db/xbps
````
The pkgbuild script in the AUR runs `./configure` with `--localstatedir=/var/lib/xbps` which differs from the way its configured in void, the AUR script is not official and this is the reason why it fails to find the pkgdb and the repodata.
Maybe use the static xbps binaries on arch linux instead of the AUR build on archlinux https://repo.voidlinux.eu/static/.

**Comment by ackalker** [comment]
@Duncaen Good catch! I will try the static xbps binaries, and perhaps I could leave a comment about the Arch PKGBUILD in the AUR.
Thanks a lot for looking into this.

**Comment by oatberry** [comment]
@ackalker I'm the maintainer of aur/xbps-git, and I believe I just fixed the PKGBUILD. Could you please rebuild it, test again, and report back?

**Comment by ackalker** [comment]
@oatberry Thanks for the quick reply! Our actions have crossed, I made the exact same change as you did and rebuilt `xbps-git` package. Succes, the problem no longer occurs.
[Here](https://gist.github.com/dd966d5f29db1d8f377a08e1eae33492) is the (hopefully final) output log of the repro script.
@Duncaen Please feel free to close this issue if you wish, sorry to have bothered you with what turned out was an Arch Linux packaging issue.

**Comment by Gottox** [comment]
I don't think this issue is solved yet as the options should not be interpreted as relative paths. Thanks for pointing this out :)

**Comment by ackalker** [comment]
@Gottox You're welcome :smile:

**Comment by Duncaen** [comment]
@Gottox we have an extra issue for relative chroot paths https://github.com/voidlinux/xbps/issues/204 I think this one can be closed, or did you mean some other relative paths?

**Comment by Gottox** [comment]
Ah, no that one can be closed then.
