### ISSUE TITLE
xbps-alternatives: dangling alternative groups when a package upgrade stops providing an alternative

### ISSUE THREAD

**Issue by CMB** [voidlinux/xbps#225]
This is probably related to issue 166.

If a package provides an alternative, and the alternative is set
to that package, the xbps alternatives code gets confused if an
upgrade to the package no longer provides the alternative.
When this happens, the alternative group is dangling, and this can
eventually trigger the following assertion in xbps-remove
(or possibly xbps-install -u):

xbps-remove: package_alternatives.c:366: xbps_alternatives_unregister: Assertion `curpkgd' failed.

It's easier to describe this with an example, so I created a couple
test branches on https://github.com/CMB/void-packages.

Check out the branch hello1 from CMB/void-packages.
Build and install helloworld.
Check out the hello2 branch.
Build and install helloworld, now at revision 2.
Build and install rot13hello.
Remove helloworld.
Try to remove rot13hello, and get an assertion for your trouble.

I originally noticed this with python3-Cython and python3.4-Cython.
python3.4-Cython no longer provides the cython alternative group.

**Comment by ebfe** [comment]
Also symlinks are not updated when the target changes on an update. voidlinux/void-packages#7521

**Comment by Duncaen** [comment]
I think this was fixed in https://github.com/voidlinux/xbps/pull/193.

**Comment by CMB** [comment]
Verified that this is fixed in git.
I thought I had tested against a git checkout when I opened this, but maybe
not.

In any case, the other alternatives issue 7521 happens with xbps from
git, so maybe these two are not related and this one could be closed.
