### ISSUE TITLE
xbps can't download packages or update repositories

### ISSUE THREAD

**Issue by lipidity** [voidlinux/xbps#227]
Hello,

My xbps-install can't sync repositories or download any packages. If I download the relevant files myself into the right places (eg a package into /var/cache/xbps) then it works fine.
I am running this on a Void Linux that has (until now) been totally trouble-free.

Here's my `xbps-install -Sd`:
[xbps-install-Sd.txt](https://github.com/voidlinux/xbps/files/679436/xbps-install-Sd.txt)
The repodata file isn't downloaded properly through xbps.
If I download the x86_64-musl-repodata file myself into the right place under /var/db/xbps then xbps is happy.

and my `xbps-install <any package not already in cache>`:
[xbps-install.txt](https://github.com/voidlinux/xbps/files/679437/xbps-install.txt)

The packages are only partially downloaded, so they fail the integrity check.
To make it work, I will download the package directly into /var/cache/xbps and then it'll install fine - I *don't* need to manually download the .sig file for it to work.

Tried it on my main system, and on another system running Arch Linux with the same results.
Tried it with the default mirror, and with this aarnet one.

If I run sshuttle to proxy all internet connections through a remote VPS, then things seem to work ok.

I'm there's a PEBKAC here somewhere, but I'm stumped.

**Comment by ebfe** [comment]
Looks like an issue with the mirror to me. Did you try another one?

**Comment by lipidity** [comment]
@ebfe I suspected that, but others also not working

> Tried it with the default mirror, and with this aarnet one.

**Comment by lipidity** [comment]
... and now it works again.

It's a mystery.
