### ISSUE TITLE
xbps-checkvers: be more forgiving

### ISSUE THREAD

**Issue by pullmoll** [voidlinux/xbps#238]
If you manage to push a broken `reverts=` line like I did with [`libclc-git`](https://github.com/voidlinux/void-packages/commit/33ea36011204b80d74df932d152ff4047d1d1a0d), one which includes also the pkgname, xbps-checkvers should either fail or be forgiving and silently remove the pkgname part.

As it is now xbps-checkvers hangs in such a case.

**Comment by ebfe** [comment]
Do you have an example invocation where it hangs? It couldn't reproduce a hang.

**Comment by pullmoll** [comment]
The linked example did hang back then when I pushed it.
`reverts=libclc-git-20160921_1`

I don't know if the hang was fixed afterwards, which would explain if it doesn't happen anymore.

**Comment by ebfe** [comment]
It still hangs. It didn't reproduce here at first since it also repends on the repo. Submitted #250 and chneukirchen/xtools#62.
