### ISSUE TITLE
Update fails: unresolvable shlib `libicui18n.so.58'

### ISSUE THREAD

**Issue by phikal** [voidlinux/xbps#240]
I just wanted to update my void system (Raspberry Pi B, glib), but suddenly this appeared ([extendend](https://gist.github.com/phikal/0a29eeaaa7ba1511f960be46092225c7)):
```
[phi@vireo ~]$ doas xbps-install -u
mpd-0.20.6_3: broken, unresolvable shlib `libicui18n.so.58'
webkit2gtk-2.16.1_1: broken, unresolvable shlib `libicui18n.so.58'
mpd-0.20.6_3: broken, unresolvable shlib `libicuuc.so.58'
webkit2gtk-2.16.1_1: broken, unresolvable shlib `libicuuc.so.58'
Transaction aborted due to unresolved shlibs.
```

I usually update the system every 2-3 days, so I'm not sure what happened here, nor how to fix it. I'm also not sure if this is an error specific to my system, or a general one. If it is, I apologize.

Also: Installing `icu`, `icu-libs` and `icu-devel` didn't help, in case anyone wants to suggest that, since I found similar suggestions on the Arch forums.

**Comment by Duncaen** [comment]
There is a big rebuild ongoing https://build.voidlinux.eu/waterfall, just wait until its finished.

**Comment by phikal** [comment]
Oh, sorry then.

**Comment by wuhanck** [comment]
@Duncaen 
I hit the issue when install node.js in pi3.
Is the big waterfall finished?

**Comment by phikal** [comment]
@wuhanck You can always look that up here: https://build.voidlinux.eu/waterfall

**Comment by wuhanck** [comment]
@phikal 
I am sorry that I try hard and don't get any clue...
Maybe just wait or I start to learn how to build one.
thanks.

**Comment by wuhanck** [comment]
@phikal 
I find that repo2.voidlinux do hold some old-version-xbps.
But we cannot access through xbps-db.
So I download icu-57, icu-libs-57 from repo2 and add to a local repo.
And I install with -R /my/local/repo icu, it works.
Hopes that it is also useful for you.
