### ISSUE TITLE
xbps-rindex doesn't like huge packages

### ISSUE THREAD

**Issue by chneukirchen** [voidlinux/xbps#243]
Details see https://github.com/the-maldridge/void-infrastructure/issues/8

**Comment by ebfe** [comment]
https://github.com/voidlinux/xbps/blob/master/bin/xbps-rindex/sign.c#L283

**Comment by ebfe** [comment]
> On Linux, read() (and similar system calls) will transfer at most
> 0x7ffff000 (2,147,479,552) bytes, returning the number of bytes
> actually transferred.  (This is true on both 32-bit and 64-bit
> systems.)
