### ISSUE TITLE
Unable to build xbps with OpenSSL 1.1

### ISSUE THREAD

**Issue by wesbarnett** [voidlinux/xbps#263]
I'm attempting to build on Arch Linux and get several errors. I ran `make -k` in an attempt to log as many errors as possible. gcc is version 7.2.0. openssl is 1.1.0.g.

    fetch/common.c: In function ‘fetch_ssl_verify_altname’:
    fetch/common.c:898:3: error: ‘ASN1_STRING_data’ is deprecated [-Werror=deprecated-declarations]
       ns = (const char *)ASN1_STRING_data(name->d.ia5);
       ^~
    In file included from /usr/include/openssl/bn.h:31:0,
                     from /usr/include/openssl/asn1.h:24,
                     from /usr/include/openssl/objects.h:916,
                     from /usr/include/openssl/evp.h:27,
                     from /usr/include/openssl/x509.h:23,
                     from /usr/include/openssl/x509v3.h:14,
                     from fetch/common.c:62:
    /usr/include/openssl/asn1.h:553:1: note: declared here
     DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
     ^
    cc1: all warnings being treated as errors
    make[1]: *** [Makefile:62: fetch/common.o] Error 1
    pubkey2fp.c: In function ‘xbps_pubkey2fp’:
    pubkey2fp.c:68:13: error: storage size of ‘mdctx’ isn’t known
      EVP_MD_CTX mdctx;
                 ^~~~~
    pubkey2fp.c:94:27: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
      if (EVP_PKEY_type(pPubKey->type) != EVP_PKEY_RSA) {
                               ^~
    In file included from /usr/include/openssl/asn1.h:24:0,
                     from /usr/include/openssl/objects.h:916,
                     from /usr/include/openssl/evp.h:27,
                     from pubkey2fp.c:16:
    pubkey2fp.c:107:26: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
      nLen = BN_num_bytes(pRsa->n);
                              ^
    pubkey2fp.c:143:2: error: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Werror=implicit-function-declaration]
      EVP_MD_CTX_cleanup(&mdctx);
      ^~~~~~~~~~~~~~~~~~
      EVP_MD_CTX_create
    pubkey2fp.c:143:2: error: nested extern declaration of ‘EVP_MD_CTX_cleanup’ [-Werror=nested-externs]
    pubkey2fp.c:68:13: error: unused variable ‘mdctx’ [-Werror=unused-variable]
      EVP_MD_CTX mdctx;
                 ^~~~~
    cc1: all warnings being treated as errors
    make[1]: *** [Makefile:72: pubkey2fp.o] Error 1
    make[1]: Target 'all' not remade because of errors.
    make: *** [Makefile:15: all] Error 1

**Comment by Gottox** [comment]
Does it help to remove `CFLAGS +=	-Werror` from config.mk?

**Comment by wesbarnett** [comment]
It does, but there are still two errors ("dereferencing pointer to incomplete type"):

    pubkey2fp.c: In function ‘xbps_pubkey2fp’:
    pubkey2fp.c:68:13: error: storage size of ‘mdctx’ isn’t known
      EVP_MD_CTX mdctx;
                 ^~~~~
    pubkey2fp.c:94:27: error: dereferencing pointer to incomplete type ‘EVP_PKEY {aka struct evp_pkey_st}’
      if (EVP_PKEY_type(pPubKey->type) != EVP_PKEY_RSA) {
                               ^~
    In file included from /usr/include/openssl/asn1.h:24:0,
                     from /usr/include/openssl/objects.h:916,
                     from /usr/include/openssl/evp.h:27,
                     from pubkey2fp.c:16:
    pubkey2fp.c:107:26: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
      nLen = BN_num_bytes(pRsa->n);
                              ^
    pubkey2fp.c:143:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
      EVP_MD_CTX_cleanup(&mdctx);
      ^~~~~~~~~~~~~~~~~~
      EVP_MD_CTX_create
    pubkey2fp.c:143:2: warning: nested extern declaration of ‘EVP_MD_CTX_cleanup’ [-Wnested-externs]
    pubkey2fp.c:68:13: warning: unused variable ‘mdctx’ [-Wunused-variable]
      EVP_MD_CTX mdctx;
                 ^~~~~
    make[1]: *** [Makefile:72: pubkey2fp.o] Error 1
    make[1]: Target 'all' not remade because of errors.
    make: *** [Makefile:15: all] Error 1

**Comment by ebfe** [comment]
On Sat, Nov 25, 2017 at 10:22:40AM +0000, James “Wes” Barnett wrote:
>     pubkey2fp.c:143:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
>       EVP_MD_CTX_cleanup(&mdctx);

No longer available in openssl 1.1+.

**Comment by wesbarnett** [comment]
Yes, I think all of these errors have to do with openssl API changes.

**Comment by ebfe** [comment]
RSA->n needs to be accessd via RSA_get0_key.

EVP_MD_CTX_{init,cleanup} changed to EVP_MD_CTX_{new,free}, and stack allocated contexts are no longer supported.

**Comment by Gottox** [comment]
OpenSSL(tm), making a bad API worse by forcing you to add #ifdefs.
