### ISSUE TITLE
Provide a way to "auto import" key.

### ISSUE THREAD

**Issue by pauldotknopf** [voidlinux/xbps#272]
Or, is there a way to manually import a repository key without prompt?

I am setting an automated install.

I get this:

```
Fingerprint: fa:bb:ce:c0:d6:72:21:9d:04:8d:b6:83:ea:4c:60:c5
Do you want to import this public key? [Y/n]
```

**Comment by maxice8** [comment]
`yes |` ?

**Comment by Vaelatern** [comment]
Copy the key in place first. Automatic acceptance of the key is quite deliberately not supported.
