### ISSUE TITLE
xbps-install: No such file or directory

### ISSUE THREAD

**Issue by DBLouis** [voidlinux/xbps#282]
When trying to install openldap, `xbps-install -Suy openldap`, I get:

    ERROR: openldap-2.4.45_4: [unpack] INSTALL script failed to execute pre ACTION: No such file or directory
    ERROR: openldap-2.4.45_4: [unpack] failed to unpack files from archive: No such file or directory

I am running up-to-date void linux in a Docker container.

**Comment by Duncaen** [comment]
I think there is something wrong with your environment and not with `xbps-install`.
Is there a `/tmp` mount and does it have the `exec` mount option?
Are the symlinks like `/lib`, `/bin` and `/sbin` to their directories in `/usr` correct?
