### ISSUE TITLE
youtube-dl-2018.05.01_1 not found during update

### ISSUE THREAD

**Issue by goosewood** [voidlinux/xbps#283]
[[*]](url) Downloading binary packages
ERROR: [trans] failed to download `youtube-dl-2018.05.01_1' package from `https://repo.voidlinux.eu/current': Not Found

On the main [repo](https://repo.voidlinux.eu/current/) it reverted back to:
python3.4-youtube-dl-2017.12.14_1.noarch.xbps

Something funny seems to have happened, probably to do with the new xbps update.

**Comment by maxice8** [comment]
It has arrived here.

Please report such issues on voidlinux/void-packages , this kind of issue already happened with *-musl arches before it just took long to sync the packages.
