### ISSUE TITLE
Can't Install GIMP: libmypaint-1.3.0b.1_1: broken, unresolvable shlib `libjson-c.so.2'

### ISSUE THREAD

**Issue by antonio-malcolm** [voidlinux/xbps#294]
System is up-to-date.
Trying to install GIMP via xbps-install, I get the following error:
libmypaint-1.3.0b.1_1: broken, unresolvable shlib `libjson-c.so.2'

**Comment by Gottox** [comment]
Your libmypaint package is outdated. Did you set it on hold or installed it from another source?

**Comment by antonio-malcolm** [comment]
No, I have none of the mypaint packages installed.

**Comment by antonio-malcolm** [comment]
AH, not installed, but referenced in an old local (and long ago unused and forgotten) repo, listed under /etc/xbps.d, and it appears as if it's checking there, first.

Commenting out the referenced line fixed this issue.
