### ISSUE TITLE
xbps-install installs dependency even though it's blacklisted with virtualpkg

### ISSUE THREAD

**Issue by freshprince** [voidlinux/xbps#296]
I have the following set:

```
# cat /etc/xbps.d/unneeded.conf 
virtualpkg=wpa_supplicant:
```

when running `xbps-remove -o` the wpa_supplicant package get's removed as an orphan.  But when I run the following with an outdated base-system

```
# xbps-install -Sun base-system
wpa_supplicant-2.6_16 install x86_64 https://alpha.de.repo.voidlinux.org/current 2071944 701676
base-system-0.112_5 update x86_64 https://alpha.de.repo.voidlinux.org/current 924
```

xbps-install want's to reinstall wpa_supplicant.

I can remove the package again with `xbps-remove -o` but shouldn't xbps-install not install wpa_suplicant as an dependency in the first place?

**Comment by freshprince** [comment]
wrong github repo -> https://github.com/void-linux/xbps/

**Comment by Duncaen** [comment]
This doesn't work as expected with virtual packages and fixing it would break other virtual package functionality. https://github.com/void-linux/xbps/pull/62

**Comment by freshprince** [comment]
Yes.  I just found this PR and subscribed to it.  Thanks for your reply.

**Comment by xtraeme** [comment]
Well, virtualpkg expects two strings delimited by :

But I agree with Duncaen,its better to use ignore for these cases.
