### ISSUE TITLE
manpage still has xtrame as author

### ISSUE THREAD

**Issue by fosslinux** [voidlinux/xbps#297]
In the xbps manpages, xtrame is still listed under the author section:
```
AUTHORS
     Juan Romero Pardines <xtraeme@gmail.com>
```

This should ideally be a developer email address or something now.

**Comment by Anachron** [comment]
This is the old repo. The new repo is here: https://github.com/void-linux/xbps

**Comment by Duncaen** [comment]
I don't think this is a valid issue.
The author doesn't change, authorship is probably defined in every possible copyright law.
If someone else authored enough to add themselves they can do that.
