### ISSUE TITLE
SHA256 hash is not valid

### ISSUE THREAD

**Issue by silvernode** [voidlinux/xbps#76]
Installing packages I have built with xbps-src pkg, now all output the error

`SHA256 hash is not valid: No such file or directory`

When I packaged yad earlier in the week it installed just fine. Now when I try to install anything I create in hostdir/binpkgs I get the aformentioned error.  I have done a clean, zap and even cloned a new copy of my forked repo. I haven't been successful in finding any information via google or any search engine with the exception of a pastebin from october last year.

[link to post](http://pastebin.com/Yqj0tMpk)

If there is anything I can do to provide clearer information I will be happy to do it. 

For what it's worth, here is [my pastebin](http://pastebin.com/ydEsER1a) of the issue.

Also doing a debug brings this up:
`[DEBUG] [trans] failed to check binpkgs: No such file or directory`
Not sure why since it finds the package in the first place

**Comment by xtraeme** [comment]
From https://github.com/voidlinux/void-packages#building-packages

```
Currently xbps expects absolute path when using the --repository option. This has been corrected in the 0.44 version.
```

Solution: use absolute paths, not relative.
