### ISSUE TITLE
Add package repository locked mode

### ISSUE THREAD

**Issue by xtraeme** [voidlinux/xbps#77]
This issue should implement a feature to be set to packages to only update a package from a specific repository. This will be useful to disallow upgrades for a package coming from an external repository, due to modified build options or compiler/linker settings.

The first example installs `foo-1.0_1` from a repository (unknown location) and then sets the `repolock` property in pkgdb to declare it as only updateable from this repository:

```
# xbps-install foo-1.0_1
# xbps-query -p repository foo-1.0_1
/my/local/repo
# xbps-pkgdb -m repolock foo
```

The `foo-1.0_1` will be updated from now on only if there's an update in the `/my/local/repo` repository, ignoring versions in other repositories.

To unlock it and accept an update of any repository:

```
# xbps-pkgdb -m repounlock foo
....
```

**Comment by Gottox** [comment]
:+1: 
Is the `hold`-flag cleared when you set repolock?

**Comment by xtraeme** [comment]
I'd think so, thanks for the reminder :+1: 

Definitely this mode should clear the `hold` mode.
