### ISSUE TITLE
Ability to skip broken shlib checks.

### ISSUE THREAD

**Issue by mid-kid** [voidlinux/xbps#82]
When an installed package has a "broken, unresolvable shlib", you can't do anything with xbps anymore to fix the problem (installing, removing packages). This should be able to be overridden.

**Comment by Gottox** [comment]
It *will* *definitely* break your system if you ignore those errors. Therefore those checks should not be ignorable.

The problem should be solved at the repo side. xbps-rindex should only add new packages if it leaves no shlibs unresolved.

**Comment by xtraeme** [comment]
I agree with @Gottox

**Comment by xtraeme** [comment]
@mid-kid note that you can perform actions, remove with -F.

**Comment by Gottox** [comment]
See #156. Most errors should be catched by rindex now.
