### ISSUE TITLE
Unresolved shlibs, cannot update.

### ISSUE THREAD

**Issue by xdave** [voidlinux/xbps#85]
full output: https://bpaste.net/show/20fcfeb6fa08

most visible errors without debug output:

demos-8.2.0_5: broken, unresolvable shlib `libglut.so.3'

libavcodec53-0.10.8_2: broken, unresolvable shlib `libx264.so.136'

Transaction aborted due to unresolved shlibs.

**Comment by Duncaen** [comment]
https://groups.google.com/d/topic/voidlinux/_XjhqGPbew0/discussion

**Comment by pulux** [comment]
have you tryed:

 for f in $(xbps-query -s '' -p transaction|cut -d ':' -f1); do sudo xbps-pkgdb $f; done

see: https://groups.google.com/forum/#!topic/voidlinux/_XjhqGPbew0

**Comment by xdave** [comment]
nepomuk-core-4.12.5_2: broken, unresolvable shlib `libavformat.so.55'

nepomuk-core-4.12.5_2: broken, unresolvable shlib `libavutil.so.52'

libavcodec53-0.10.8_2: broken, unresolvable shlib `libx264.so.136'

Transaction aborted due to unresolved shlibs.

more broken now than before

**Comment by xtraeme** [comment]
Those packages were removed long ago from void-packages... they were built against an older ffmpeg version and now there's no pkg providing them.

You should remove them (with -F) or create the pkgs providing them :-)

xbps 0.44 is stricter and does not allow you to install pkgs with shlibs that are not resolved, thanks.

**Comment by radare** [comment]
I am able to reproduce this issue too. and the solutions seems to be to find which pkgs are providing the missing shlibs and removing them.

Then xbps-install -Syu` was failing because i didnt had enough free space, so i did the manual way:
```
xbps-query -s. | cut -d '-' -f 1 | awk '{print $2}' | xargs xbps-install -yu
```

I guess there's a best way to do all this stuff
