### ISSUE TITLE
http/ftp proxy

### ISSUE THREAD

**Issue by maaca** [voidlinux/xbps#86]
Is it possible to use xbps over proxy? I've tried to use system variables http_proxy/https_proxy/ftp_proxy, searched for keyword in the configuration, but no success. Have I missed something in the documentation?

**Comment by agustri** [comment]
you actually can use http_proxy via enviroment variable, but the last time I tried it still doesn't support authenticated proxy

**Comment by maaca** [comment]
That explains a lot. My proxy is authenticated. :-(

**Comment by xtraeme** [comment]
HTTP and FTP proxies are supported.

Quoting libfetch(3) from NetBSD
```

EXAMPLES
     To access a proxy server on proxy.example.com port 8080, set the
     HTTP_PROXY environment variable in a manner similar to this:

           HTTP_PROXY=http://proxy.example.com:8080

     If the proxy server requires authentication, there are two options avail-
     able for passing the authentication data.  The first method is by using
     the proxy URL:

           HTTP_PROXY=http://<user>:<pwd>@proxy.example.com:8080

     The second method is by using the HTTP_PROXY_AUTH environment variable:

           HTTP_PROXY=http://proxy.example.com:8080
           HTTP_PROXY_AUTH=basic:*:<user>:<pwd>

     To disable the use of a proxy for an HTTP server running on the local
     host, define NO_PROXY as follows:

           NO_PROXY=localhost,127.0.0.1
```

**Comment by xtraeme** [comment]
I just tested this and seems to work as expected.

Closing this because there's no issue.
