### ISSUE TITLE
void Linux install wm not possible anymore since 03-26-2015

### ISSUE THREAD

**Issue by jetta20162** [voidlinux/xbps#87]
A Windows Manager can not be installed anymore due to unresolved dependencies, the hicolor-icon-theme is missing in the repository.

**Comment by bougyman** [comment]
What Windows Manager?

**Comment by jetta20162** [comment]
I tried xfce4 and enlightenment. I think it is a General problem

**Comment by xtraeme** [comment]
This is not the correct place to submit package issues... anyway I've restarted the build and hicolor-icon-theme is now available.

Next time use the void-packages repository to submit package issues.

This one is exclusive for xbps.
