### ISSUE TITLE
void-live-x86_64-latest-xfce.iso doesn't load

### ISSUE THREAD

**Issue by fcops** [voidlinux/xbps#88]
On trying to load it flashes a message like

    specified group 'kvm' unknown

then it blanks and loops...

**Comment by Gottox** [comment]
Did you use qemu?

**Comment by fcops** [comment]
I loaded with Easy 2 Boot. Void live with base-system for x86_64 gave the same error line but worked.

**Comment by xtraeme** [comment]
This is not the proper repository to report such errors about live images, use voidlinux/void-mklive instead.

Meanwhile make sure that you've downloaded the iso images that were created some days ago.
