### ISSUE TITLE
Question: Support for multiple package versions

### ISSUE THREAD

**Issue by dumblob** [voidlinux/xbps#89]
Is there any support for full-featured handling of multiple versions of packages (including their dependencies) other than creating a new package with the version in it's name?

E.g. I'd like to have a "stable" system (i.e. few hundreds of packages, which I don't want to upgrade for e.g. 3 years) and in the meantime I'd like to only **add** (not upgrade) certain important new versions of "end-user-space" packages (like PostreSQL or Apache with many modules etc.). After three years, I could end-up with 3 parallel installations of Apache and 4 parallel installations of PostgreSQL, but the whole rest of the system would be 3 years old. After these 3 years, I'd like to update the whole system while preserving the two newest installations of Apache and PostreSQL.

Is it possible? If not, is it planned?

**Comment by xtraeme** [comment]
You can use a different repo for a pkg and its dependencies:

` /my-repo/pkg-1.2/...`
`/my-repo/pkg-2.0/...`

and use `xbps-pkgdb(8) -m repolock` to avoid updating pkgs from other repositories.

But a repository does not allow multiple package versions of the same package to co-exist. A package name must be unique.

**Comment by dumblob** [comment]
If I understood you correctly, the outlined example is impossible to implement using *xbps* as even if I can use more repos at the same time (e.g. separate repos for each Apache version and separate repos for each PostreSQL version), there is no way how to *setup* different environments with some mixture of packages from different repositories (e.g. in shell1: `Apache 33.5 with PostgreSQL 87.3` and in shell2: `Apache 49.7 with PostgreSQL 63.1`).

**Comment by xtraeme** [comment]
You can add any pkg to a repository as you prefer, but a repository cannot have two packages with the same package name.

What you want to accomplish can be made already using multiple repositories.

**Comment by dominikh** [comment]
OP wants to install multiple versions of the same package on the same system. Having multiple repositories won't help here if the package has the same name in all repositories.

Also, there'd be file conflicts because we do not in any way contain installed packages in versioned directories.

**Comment by xtraeme** [comment]
@dominikh you are right. xbps does not allow multiple package versions to coexist at the same time, because the installation prefix is global (/). 

Regarding file conflicts, this is just another design fail.

If you want something like that use nix, or stow, or something like that.

**Comment by dumblob** [comment]
It's exactly as @dominikh said. Yes, I know about Nix (and it's "full-featured" counterpart Guix). I didn't know about Stow, but it seems, that it doesn't integrate in any other tool, so the package management would be very fragile and therefore I doubt anybody would like to use it e.g. on a production system.

Closing this issue as resolved - "not supported by xbps and there are no plans to support it".

**Comment by xtraeme** [comment]
I never said "no plans to support it".

In fact I'm aware of such design decisions I made in the past, and my next implementation will exactly support multiple package versions, atomic updates and rollback support.

But not ETA :-)

**Comment by dumblob** [comment]
>I never said "no plans to support it".

Correct. I just wanted to push you to publish your hidden intents :)

>In fact I'm aware of such design decisions I made in the past, and my next implementation will exactly support multiple package versions, atomic updates and rollback support.

Great news. Will it be implemented as a new (major) version of *xbps* or rather as a separate project? I would like to follow this (and try to help). That's why I'm asking.

>But not ETA :-)

Sure, understood.

**Comment by dumblob** [comment]
>Will it be implemented as a new (major) version of xbps or rather as a separate project?

Any decisions made on this?

**Comment by Gottox** [comment]
Afaik no.
