### ISSUE TITLE
Disable signature check temporary

### ISSUE THREAD

**Issue by thypon** [voidlinux/xbps#98]
Right now i'm compiling packages for my machines on a remote server automatically. The repository is at `http://pompel.me` right now. And the command i give is:

```
sudo xbps-install -Sf -R http://repo.pompel.me fontconfig freetype cairo dmenu
```

The error i got is
```
ERROR: [trans] failed to download `dmenu-4.5_10' signature from `http://repo.pompel.me': Not Found
```

The repository it's obviously unsigned given it's a personal repository. Would be good to have an option to disable temporary signature check.

**Comment by beefcurtains** [comment]
It's a much better idea to create your own keypair and add the public part to your machines. These sort of things create the potential for abuse by people who don't know what they're doing, and people who know exactly what they're doing but are being malicious. What if your package depends on a void package? Are those signatures ignored, too? I think there are more people installing packages than creating repositories, so I'd rather keep the design balanced that way. Plus you can install your own packages on the go if you sign them.

**Comment by thypon** [comment]
Maybe we could add unsigned repositories with -U flag (like archlinux). It's really a mess to distribute a key where you know that the repository is in your subnetwork/vpn.

**Comment by xtraeme** [comment]
Remote repositories are explicitely signed with RSA explicitely.

I won't add support for unsigned remote repositories, if you want that, use sshfs.
